### ISSUE TITLE
ShutterBox

### ISSUE THREAD

**Issue by JustThe2ofUs** [Piotr-Grochowski/homey-blebox#1]
Hi; 
I see that Shutterbox and Dimmerbox are more or less the same hardware. 
Can I use Shutterbox w/ the App in Homey it do I have to send it back?

**Comment by Piotr-Grochowski** [comment]
I did not implement shutterBox yet in the app, because I have no shutters to test it. I can try to make an implementation if you'd like to make a test.

**Comment by Piotr-Grochowski** [comment]
Hello,
It took me some time, but I've prepared a new version with shutterBox support. I just submited it to Athom in beta. Are you interested in testing it?
