### ISSUE TITLE
Homey: AirSensor -  Wrong device type: undefined

### ISSUE THREAD

**Issue by whizoh** [Piotr-Grochowski/homey-blebox#11]
Adding device to Homey and filling corect IP address it shows an error: X Wrong device type: undefined

**Comment by Piotr-Grochowski** [comment]
Hello, 
I think there is a version mismatch problem. Blebox updated many firmwares without informing developers like me, so homey driver for blebox might be out of date. Could you please send me:
- firmware version
- API level 
of your airSensor?
You can find it on the setting page, on the bottom (you may also send me a screenshot from the app with those infos).
I'll manage to update the driver in the following days, it's quite busy time in my primary job at the moment.

**Comment by whizoh** [comment]
![obrazek PNG](https://user-images.githubusercontent.com/92819216/157743719-1caeb857-7ba3-4ec7-9b7e-0cf8ea655b46.png)

Problem nadal występuje. Zarówno w wersji aplikacji na homey: eperimental jak i normalnej

**Comment by Piotr-Grochowski** [comment]
Dotychczasowy sterownik dla Homey był przystosowany do poprzedniego firmware airSensora i poprzedniego poziomu API. Zaktualizowałem do najnowszego - w wersji testowej apki (2.4.6). Prosiłbym o jej zainstalowanie, test i potwierdzenie, czy już jest OK. U mnie działa.

**Comment by whizoh** [comment]
![obrazek PNG 2](https://user-images.githubusercontent.com/92819216/157919147-1350ac78-28ed-4f4a-b14e-46596c633496.png)
Poszło kawałek dalej. Widzi airsensor ale nowy błąd się pojawia.

**Comment by Piotr-Grochowski** [comment]
Poprawione, wersja testowa 2.4.7 powinna już zadziałać. Potrzebna była jeszcze jedna zmiana pod nowe API.

**Comment by whizoh** [comment]
Działa. Dziękuję.
