### ISSUE TITLE
Can't add device gatebox

### ISSUE THREAD

**Issue by bartekkostrzewa** [Piotr-Grochowski/homey-blebox#12]
I have a problem with your app. I can't add blebox gatebox into homey. 
I am putting gatebox ip:192.168.1.158 from my home network and
Username and password that  I have created in blebox app In local authorisation settings. I'm getting message in homey :could not find that pair session. What should I do?

**Comment by bartekkostrzewa** [comment]
Jeśli blebox nie ma przyporządkowanego hasła i użytkownika pojawia się komunikat:wrong device type :undefined

**Comment by Piotr-Grochowski** [comment]
Możesz mi podesłać wersję firmware oraz API Level twojego gateboxa? Blebox zaktualizował wiele firmwareów bez informacji dla developerów takich jak ja i możliwe, że sterownik Homeya jest nieaktualny. Informacje te znajdziesz na dole strony ustawień gateboxa (możesz przysłać np. screenshot z apki). W najbliższych dniach postaram się zaktualizować sterownik dla Homeya - jak tylko znajdę parę chwil, bo mam teraz sporo na głowie...
