### ISSUE TITLE
ProxiBox

### ISSUE THREAD

**Issue by dirkg173** [Piotr-Grochowski/homey-blebox#13]
Hi Piotr,

is it possible to add the [BleBox ProxiBox](https://blebox.eu/product/proxibox/?lang=en)?
I would like to be able to switch an LED strip in the kitchen on and off with the ProxiBox.

Example
When...
-- Proximity alarm turns on
And...
-- Lamp is switched off
Then...
-- Switch on lamp
Else...
-- Switch off lamp

Would this be possible?

Thx in advance!

Best regards
Dirk

**Comment by Piotr-Grochowski** [comment]
Hello,
I don't own proxiBox so it may be a bit hard, but I can try to manage to do it - if you would like to test my beta-versions. I would prepare some code and publish test version of homey blebox driver - I would then send you a link for installation and then I would need some feedback from you. I would also send you some links to connect to proxiBox so you would use them in your browser and send me back what you see as a result. May we work in this way?

**Comment by dirkg173** [comment]
Hi Piotr,
it's not a problem for me to test your beta versions if these versions are released in the official app store. Installing an app via CLI might be difficult for me. So we can do it the way you suggested.

Thank you very much for your support!

Best regards
Dirk

**Comment by Piotr-Grochowski** [comment]
Yes it will be a beta version in the official App Store.

For the beginning please visit in your web browser URL:

http://proxiIP/info

where proxiIP is the IP address of your proxiBox. Then please paste me back the response of the server.

**Comment by dirkg173** [comment]
Great!

Because I ordered the ProxiBox after you said that you are trying to integrate the ProxiBox, I currently do not have the ProxiBox yet. But I assume that the box will be delivered on Wednesday - Thursday. Then I will provide you with the necessary data.

**Comment by dirkg173** [comment]
This is the info you asked for:

`{"device":{"deviceName":"proxiBox","type":"buttonBox","product":"proxiBox","hv":"proxB.1.0","fv":"0.1011","universe":0,"apiLevel":"20200831","id":"f6cfa27baceb","ip":"192.168.178.70","availableFv":"0.1011"}}`

**Comment by Piotr-Grochowski** [comment]
Hello,
I checked with BleBox technical documentation, and there is no API in proxiBox. I can see it can be used just like actionBox I own and use with Homey. Below I will write you what to do to use it - no BleBox Homey App update needed!
1. Install Homey App named "HTTP request flow cards". It will add Homey support for web requests (proxiBox makes web requests to the URL you provide) and additional card to use them in flows. 
2. Preapre a new flow - just like you have written in your first message above. For the WHEN part please use: HTTP request flow cards - "Incoming GET". As the parameter please use the name of the webservice (it can be anything, with just latin letters and digits, not special character or spaces; it also has to be unique for any new flow). E.g.: "proxiBoxTestWebService".
3. Go to BleBox App -> your proxiBox configuration page (or use your computer's browser with proxiBox IP address)
4. In Actions section please create a new Action. I don't know exact parameters for proxiBox (if you'll have any trouble please send me the screenshot). The important parameter is the action type - it should be something like "Go to URL" or similar (I use polish version of the interface). If you choose it then you can write the URL: http://HOMEYIPADDRESS/api/app/com.internet/proxiBoxTestWebService
5. In the above URL you should replace HOMEYIPADDRESS with actual LAN IP address of your Homey. Also if you create any other name for the webservice (or more webservices), change proxiBoxTestWebService to another name.
6. After saving your proxiBox should start the flow in Homey. If it doesn't work please paste the above URL to your web browser and see what the response is.

I hope you won't have any problems to use proxiBox with Homey! My actionBoxes work fine, so I think it will be OK!
Have fun!

Piotr

**Comment by dirkg173** [comment]
Hi Piotr,

Thank you for your efforts and the detailed explanation.
Isn't an "HTTP Request" also doable with the on-board tools from Homey?

**Comment by dirkg173** [comment]
Hi Piotr,

Thank you very much for the support and the detailed explanation.
Isn't an "HTTP Request" also doable with the on-board tools from Homey?

So I tried to make a "HTTP Request" like you explained.
This is how I configured an Action (sorry, only in German). 192.168.178.50 is the ip address of Homey:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/40319629/141642697-abc103d9-eb43-409b-8f64-0818f47c9fd5.png">

And this is the flow in Homey:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/40319629/141642934-e92fc7e3-fbc2-4e9f-9c75-607b6b1c225c.png">

But it doesn't work. This is what I get, if I paste the URL in a web browser:
`{"code":401,"error":"not_logged_in","error_description":"You need to log in to access this resource"}`

Do you know what is wrong?
Sorry, but I have no idea about "HTTP Request".

**Comment by Piotr-Grochowski** [comment]
Hello,
Please check the HTTP Request App settings page - "require authorization on API" should be disabled. I think you have this option turned on (it's default I think). Please go to the configuration page and disactivate the authorization.

**Comment by dirkg173** [comment]
Hello,
you're right, "require authorization on API" was enabled.
But after disable this option, I receive the sam failure message:
`{"code":401,"error":"not_logged_in","error_description":"You need to log in to access this resource"}`

**Comment by Piotr-Grochowski** [comment]
Hello again,
I found on the Homey community forum that you should make a restart after changing this option do disabled. So please restart and try again (I don't know if you should restart only the App or the whole Homey - try with the App first, and if it still does not work - restart Homey). Please let me know.

Piotr

**Comment by dirkg173** [comment]
Hello Piotr,
I had to restart Homey and then the app. In addition I had to configure the action event at the ProxiBox, but now it works.
Thx a lot for your support!

Best regards
Dirk

**Comment by dirkg173** [comment]
SOLVED

**Comment by Piotr-Grochowski** [comment]
Thank you for supporting this App. I really appreciate it!
