### ISSUE TITLE
proxyBox

### ISSUE THREAD

**Issue by rlucian** [Piotr-Grochowski/homey-blebox#14]
is ProxyBox supported? any plans to support it for homey?

**Comment by Piotr-Grochowski** [comment]
You don't need any integration for proxiBox (or actionBox). Using this device you can connect to other BleBox devices (e.g. switchBox, dimmerBox, etc.) or you can run any web service. If you would like to use it with Homey, just install an App called HTTP request flow cards and configure it, then create a flow, that you'd like your proxiBox to run using "Incoming GET" flow card in WHEN section. In your proxiBox configuration - add an action to run a web URL using your new web service.
