### ISSUE TITLE
Problem with wilightbox - "Wrong device type: wLightBox"

### ISSUE THREAD

**Issue by PawelPalusz** [Piotr-Grochowski/homey-blebox#15]
When trying to configure with homey I get an error when trying to add a device "Wrong device type: wLightBox"
is there any way to solve this problem? On the homey forum a year ago someone also had this problem and it was not resolved
error thread https://community.homey.app/t/problems-with-blebox-wlightbox/43210

**Comment by Piotr-Grochowski** [comment]
Please install test version of the app - it uses the new API, that your wLightBox uses I think. It's here: https://homey.app/pl-pl/app/eu.blebox/BleBox/test/
