### ISSUE TITLE
tempSensor are not work

### ISSUE THREAD

**Issue by selzilla** [Piotr-Grochowski/homey-blebox#16]
Version 3.0.1

The temperatures of the tempSensor are no longer displayed in Homey.
After updating to the beta version, I have re-taught the device, but unfortunately I only get the display: Last value unknown.

**Comment by Supra66** [comment]
Hi same problem here. I have  5 tempsensors no one is working since today.

**Comment by Friggasvej** [comment]
Same, just rolled back to the non beta and everything works perfect again.
Dident even have to pair the devices..

**Comment by Supra66** [comment]
> 

I don't know how to roll back on Homey :-(

**Comment by Friggasvej** [comment]
Install from this link
https://homey.app/en-us/app/eu.blebox/BleBox/

**Comment by Supra66** [comment]
> Install from this link https://homey.app/en-us/app/eu.blebox/BleBox/

Doesn't work for me the 3.1.0 version isn't working for me the last working was 3.0.1 but I don't know how to roll back from 3.1.0 to 3.0.1

**Comment by selzilla** [comment]
Going back to stable 3.1.0 did not work for me. Here, too, the sensors now refuse to work.
I have now registered them in Home Assistant. They work immediately. I now send them from there to Homey via MQTT. It now works without the app.

**Comment by selzilla** [comment]
Going back to stable 3.1.0 did not work for me. Here, too, the sensors now refuse to work.
I have now registered them in Home Assistant. They work immediately. I now send them from there to Homey via MQTT. It now works without the app.

**Comment by Piotr-Grochowski** [comment]
Hello, did you all te-create all the devices when updated the app from v2 to v3?

**Comment by stevenv2201** [comment]
Same problem with TempSensor here. I could re-add the sensors,  but temperatures are not shown. I did not remove the “old” tempsensors which were added in v2

**Comment by Piotr-Grochowski** [comment]
Found the bug. Please install test version: https://homey.app/pl-pl/app/eu.blebox/BleBox/test/
and let me know if it works OK now.

**Comment by stevenv2201** [comment]
Installed the test version, but problem remains. Temperatures are not shown. Should The existing devices be removed and added again?

**Comment by Piotr-Grochowski** [comment]
If you re-created the device in version 3+ then there should be no need to do it again. Unfortunately I don't own a tempSensor so I can't test it myself. I think there might be another bug - next test version published - check it. If it won't work then please issue in your browser http://IP/state where IP is the IP address of your tempsensor and then please send me back the result. Thanks.

**Comment by stevenv2201** [comment]
Removed the working device and re-added, but no longer seems to work…

**Comment by Piotr-Grochowski** [comment]
What poll time do you have in your advanced settings of both tempSensors?

**Comment by stevenv2201** [comment]
1000ms for both

**Comment by Piotr-Grochowski** [comment]
One more try: delete both devices, restart the app (ensure its 3.1.2), add tempSensors, wait 1-2 minutes and tell me what is the result.

**Comment by Piotr-Grochowski** [comment]
You can also try restarting Homey. I noticed some problems when upgrading apps from SDK2 to SDK3

**Comment by stevenv2201** [comment]
deleting, restarting app, adding sensors again and then restarting Homey itself: didn’t solve the issue.  Both sensors don’t receive temp data. Further testing will be for tomorrow…

**Comment by Piotr-Grochowski** [comment]
OK. For me it's totally weird that it worked for a short moment. It should work or not - all the time...

**Comment by stevenv2201** [comment]
Weird indeed. Maybe revert to 3.1.1? Maybe one of the sensors received data while still at 3.1.1 at the moment that I was installing 3.1.2?

**Comment by Piotr-Grochowski** [comment]
I don't think so. Looking at the results you've provided - 3.1.2 should be the one.
May you please send me the screenshots of your advanced settings page?

**Comment by stevenv2201** [comment]
![DAF0F1B6-1D17-4548-9755-0216882EB971](https://user-images.githubusercontent.com/96480482/197626699-085d3514-b8c8-42e4-99d6-5f6a45d6b98a.png)
![75C22F9D-2AAB-402D-B0DC-07B7BF638982](https://user-images.githubusercontent.com/96480482/197626702-fa03c59b-c471-4e2e-b379-c3d5be0d938a.png)

**Comment by Piotr-Grochowski** [comment]
I'd like to get any more comments reg. the test version - does anyone manage it to work or does it not work for everyone?

**Comment by Supra66** [comment]
> I'd like to get any more comments reg. the test version - does anyone manage it to work or does it not work for everyone?

Hi i tester the 3.1.2 and for me it seems to work now!
![Uploading Screenshot_20221025-051720_Homey.jpg…]()

**Comment by Supra66** [comment]
> I'd like to get any more comments reg. the test version - does anyone manage it to work or does it not work for everyone?

Hi i tested the 3.1.2 now and for me it seems to work now!
![Screenshot_20221025-051720_Homey](https://user-images.githubusercontent.com/94135198/197674729-13a117a6-95d9-4d0a-a0ca-539f277aa961.jpg)

**Comment by stevenv2201** [comment]
Works now for me as well. The trick was - believe it or not - restart my iPhone! A glitch in the homey app maybe. Anyway, it is solved now 😄. Thanks for your support!

**Comment by Piotr-Grochowski** [comment]
Great, good to know. I'll notice Athom to put this version to production.
