### ISSUE TITLE
Gatebox

### ISSUE THREAD

**Issue by lindblomstefan** [Piotr-Grochowski/homey-blebox#2]
Hi, I have a [Gatebox](https://blebox.eu/en/products/11-gatebox-gate-and-door-controller-for-iphone-and-android.html) supplied with my Wisniowski garage door. Would be lovely to have even this device implemented :)

**Comment by lindblomstefan** [comment]
If you make an implementation I can try it out. I have it connected to my garage motor, as well sensors to identify open/closed/neither open or closed. Let me know if you need any input.

**Comment by Piotr-Grochowski** [comment]
Hello,
I'll try to implement it and I'll send it to you for some tests - but due to holiday time I think I will be able to do it after August.

**Comment by lindblomstefan** [comment]
Well, then I wish you a good holiday :)

**Comment by Athomsson** [comment]
Gallo, did it work With the blebox garagedoor opener? Hos do i do?

**Comment by Piotr-Grochowski** [comment]
No, it's not yet supported, but I plan to do it in the next weeks. So stay tuned!

**Comment by Piotr-Grochowski** [comment]
Hello guys, I'm ready to prepare gatebox implementation. Unfortunatelly there is no such device type in Homey like gate, door or garagedoor. I have to do it using other device types, but to choose the proer ones I'd like to get some more informations from you about how the gatebox is working with your gate/door, how do you use it, what exactly do you need. Please contact me in private message, so I'd be able to ask some questions.

**Comment by Athomsson** [comment]
Hello! Iam only using my gatebox to send a signal too my motor to Open/close.

https://www.wisniowski.pl/se/foer-hemmet/smart-teknik/wicontrol

________________________________
Från: Piotr-Grochowski <notifications@github.com>
Skickat: den 21 oktober 2019 21:05
Till: Piotr-Grochowski/homey-blebox <homey-blebox@noreply.github.com>
Kopia: Athomsson <ante_thomsson@hotmail.com>; Comment <comment@noreply.github.com>
Ämne: Re: [Piotr-Grochowski/homey-blebox] Gatebox (#2)


Hello guys, I'm ready to prepare gatebox implementation. Unfortunatelly there is no such device type in Homey like gate, door or garagedoor. I have to do it using other device types, but to choose the proer ones I'd like to get some more informations from you about how the gatebox is working with your gate/door, how do you use it, what exactly do you need. Please contact me in private message, so I'd be able to ask some questions.
