### ISSUE TITLE
BleBox Tempsensor

### ISSUE THREAD

**Issue by C0kedk** [Piotr-Grochowski/homey-blebox#3]
Any chance the Blebox temp sensor can be supported?

https://blebox.eu/en/products/39-tempsensor-temperature-sensor.html

This would be perfect for an simple solution for boiler control etc.

**Comment by Piotr-Grochowski** [comment]
Yes, it will be supported. I already bought it, so in the near future I will add this new device to the driver. I have to upgrade the driver first for the Homey 3.0.0, which is already out for developers and will be available for the users in the end of this month.

**Comment by C0kedk** [comment]
Sweet, thanks! 🙂👍

**Comment by Piotr-Grochowski** [comment]
tempSensor implementation is ready. I already published v1.5.0 in git and sent request to Athom for a review. As soon as they do it, the new version should be published and installed on your Homey. Please let me know how it worked for you - during my short tests I had no problems.

**Comment by C0kedk** [comment]
At holidays right now, report back as soon im back
