### ISSUE TITLE
Need some help with gateBox

### ISSUE THREAD

**Issue by Athomsson** [Piotr-Grochowski/homey-blebox#4]
Hello guys, I'm ready to prepare gatebox implementation. Unfortunatelly there is no such device type in Homey like gate, door or garagedoor. I have to do it using other device types, but to choose the proer ones I'd like to get some more informations from you about how the gatebox is working with your gate/door, how do you use it, what exactly do you need. Please contact me in private message, so I'd be able to ask some questions.

_Originally posted by @Piotr-Grochowski in https://github.com/Piotr-Grochowski/homey-blebox/issues/2#issuecomment-544660919_

Hello! Iam only using my gatebox to send a signal too my motor to Open/close.

https://www.wisniowski.pl/se/foer-hemmet/smart-teknik/wicontrol

**Comment by Piotr-Grochowski** [comment]
Do you use just 1 button in the app to open and close or do you use separate buttons? I can see this device has two outputs (primary and secondary), but I don't know what are they used for. Also I can see that there is a possibility to get a state of the device (opened, closed, or how much it is closed in % - after a calibration as I understand). Do you use it?

**Comment by Athomsson** [comment]
only one button, i think it inly 1 line you can use 4 the ''door'' and line 2 is if you want like notifikation light or somthing.

Hmm i dont think i can do that on mine? i dont use it enyways only the output signal 4 open/close

________________________________
Från: Piotr-Grochowski <notifications@github.com>
Skickat: den 22 oktober 2019 08:48
Till: Piotr-Grochowski/homey-blebox <homey-blebox@noreply.github.com>
Kopia: Athomsson <ante_thomsson@hotmail.com>; Author <author@noreply.github.com>
Ämne: Re: [Piotr-Grochowski/homey-blebox] Hello guys, I'm ready to prepare gatebox implementation. Unfortunatelly there is no such device type in Homey like gate, door or garagedoor. I have to do it using other device types, but to choose the proer ones I'd ...


Do you use just 1 button in the app to open and close or do you use separate buttons? I can see this device has two outputs (primary and secondary), but I don't know what are they used for. Also I can see that there is a possibility to get a state of the device (opened, closed, or how much it is closed in % - after a calibration as I understand). Do you use it?

**Comment by Piotr-Grochowski** [comment]
OK, got it. So i think in the begining i will just make a driver with one stateless buton and that's it. If there will be someone else with gatebox in another configuration, then I will upgrade the driver. 
Because if I understand it right, you may have connected some limiters/contactrons, so gatebox knows if the gate is closed or opened. And then if I would make some sensors for that in homey driver, then you may have some flows like "if the gate get's opened -> turn on the light in garage" or "if the gate get's opened and the home-alarm is armed, then turn on the siren". But I would need someone with those lines connected to gatebox to be able to test it. 

So summarizing - at the moment I will make a driver with just a stateless button. I will let you know as soon as it is ready (I think this week) to test it.

**Comment by Athomsson** [comment]
Ye thats right, the how far its open/close the gate are confiq in the ''motor''..

Sounds good man, good work!
________________________________
Från: Piotr-Grochowski <notifications@github.com>
Skickat: den 22 oktober 2019 10:05
Till: Piotr-Grochowski/homey-blebox <homey-blebox@noreply.github.com>
Kopia: Athomsson <ante_thomsson@hotmail.com>; Author <author@noreply.github.com>
Ämne: Re: [Piotr-Grochowski/homey-blebox] Hello guys, I'm ready to prepare gatebox implementation. Unfortunatelly there is no such device type in Homey like gate, door or garagedoor. I have to do it using other device types, but to choose the proer ones I'd ...


OK, got it. So i think in the begining i will just make a driver with one stateless buton and that's it. If there will be someone else with gatebox in another configuration, then I will upgrade the driver.
Because if I understand it right, you may have connected some limiters/contactrons, so gatebox knows if the gate is closed or opened. And then if I would make some sensors for that in homey driver, then you may have some flows like "if the gate get's opened -> turn on the light in garage" or "if the gate get's opened and the home-alarm is armed, then turn on the siren". But I would need someone with those lines connected to gatebox to be able to test it.

So summarizing - at the moment I will make a driver with just a stateless button. I will let you know as soon as it is ready (I think this week) to test it.

**Comment by lindblomstefan** [comment]
Hi, I have sensors connected to the gate box which tells me if the gate is open, half open (during opening or closing) and closed. There are two sensors connected and when a magnet hits either sensors it is either open or closed. If the magnet isn’t close to any sensor then half open.

S1 and S2 in this picture: https://neoled.com.pl/public/assets/images/blebox-gatebox-schemat.JPG

**Comment by Piotr-Grochowski** [comment]
Thanks for the additional info. Do you also use only 1 button to open/close the gate? Regarding half-open - do I understand it right, that you don't get exact position of the gate (e.g. opened in 30%), only the information that it is moving at the moment?

**Comment by lindblomstefan** [comment]
Yes, one button

Correct in the sense that I don’t know how open or closed. However, it could be standing still instead of moving but assume you took that into account :)

Button looks like this and status of the gate in this case is “half-open” :)
https://homeso.eu/918-tm_thickbox_default/sterownik-gatebox-automatyczne-otwieranie-bram.jpg

**Comment by lindblomstefan** [comment]
Awesome 👌

**Comment by Piotr-Grochowski** [comment]
Hello, I've got a first version for testing, with just a button. Before I post it I have a request to you guys. May you please check in your browser two pages?
Please navigate with your browser to:
http://192.168.2.164/api/device/state
where 192.168.2.164 change with IP address of your gateBox. Please paste me the text which you will see, it will be something like this:

{"device":{"deviceName":"Lampka nocna","type":"switchBox","fv":"0.927","hv":"7.5","universe":0,"apiLevel":"20180604","id":"ee1aba19fc6f","ip":"192.168.2.164","availableFv":null}}

The second age is under address:
http://192.168.2.164/s/p
Again please change 192.168.2.164 with IP address of your device. In the same moment you navigate to this URL, your gate should open/close (depending on it's state) - just like you would press the in wBox app. Please confirm me if it worked.

Thanks in advance!

**Comment by lindblomstefan** [comment]
I’ll check during the evening when the kids are asleep :)

**Comment by lindblomstefan** [comment]
Firat one
{"deviceName":"Garageport Ã¶ppna/stÃ¤nga","type":"gateBox","fv":"0.611","hv":"7.2","id":"5ecf7fd2a7de","ip":"10.0.1.39"}

Ã¶ppna = Open (Öppna in Swedish)
stÃ¤nga = Close (Stänga in Swedish)


Second

{"gate":{"currentPos":0,"desiredPos":50,"extraButtonType":1,"extraButtonRelayNumber":1,"extraButtonPulseTimeMs":800,"extraButtonInvert":0,"gateType":1,"gateRelayNumber":0,"gatePulseTimeMs":800,"gateInvert":0,"inputsType":0,"openLimitSwitchInputNumber":0,"closeLimitSwitchInputNumber":1}}

Haha, got a notification that the garagedoor opened (was closed) when running this in the browser. Guess it works then.

**Comment by Piotr-Grochowski** [comment]
Thanks for your tests. I made some bugfixes to the code (there are some mistakes in BleBox technical documentation). The gateBox implementation is ready. I made two functionalities there:
- a stateless button to open/close the gate
- a contact alarm sensor to notice if the gate is opened or closed (if the gate is opened then the alarm is on)

So not only you should be able to use the button, but also you can use this device in flows (e.g. if the gate opens -> turn on the light in garage).

I will now send the app for a review to Athom - it will be v 1.8.0 in BETA channel (if you use STABLE channel then you will need to switch to BETA). Usually they check the app within 1-2 business days and then the app will be published so you will be able to test yourself. I will give here a notice as soon as the app is accepted.

**Comment by Athomsson** [comment]
Hallo, liten late but my say
1, {"deviceName":"My RiCo","type":"gateBox","fv":"0.611","hv":"0.6","id":"5ecf7f1885bd","ip":"192.168.1.186"}

2, {"gate":{"currentPos":50,"desiredPos":50,"extraButtonType":2,"extraButtonRelayNumber":1,"extraButtonPulseTimeMs":800,"extraButtonInvert":1,"gateType":1,"gateRelayNumber":0,"gatePulseTimeMs":800,"gateInvert":0,"inputsType":1,"openLimitSwitchInputNumber":0,"closeLimitSwitchInputNumber":1}}

Skickat från min iPhone

30 okt. 2019 kl. 20:25 skrev Piotr-Grochowski <notifications@github.com>:

﻿

Thanks for your tests. I made some bugfixes to the code (there are some mistakes in BleBox technical documentation). The gateBox implementation is ready. I made two functionalities there:

  *   a stateless button to open/close the gate
  *   a contact alarm sensor to notice if the gate is opened or closed (if the gate is opened then the alarm is on)

So not only you should be able to use the button, but also you can use this device in flows (e.g. if the gate opens -> turn on the light in garage).

I will now send the app for a review to Athom - it will be v 1.8.0 in BETA channel (if you use STABLE channel then you will need to switch to BETA). Usually they check the app within 1-2 business days and then the app will be published so you will be able to test yourself. I will give here a notice as soon as the app is accepted.

**Comment by Piotr-Grochowski** [comment]
Thanks!

**Comment by Piotr-Grochowski** [comment]
v1.8.0 is out in BETA channel - please install it and make some tests. Please give me some feedback if it works for both of you!

**Comment by lindblomstefan** [comment]
After entering the IP address and hitting “Connect” this message appears:  Cannot read property 'id' of undefined

**Comment by Piotr-Grochowski** [comment]
I found the bug and I've corrected it. I can make a fast-publish as an alpha version - so we won't need to wait for athom to review it and you will be immediately able to install the new version. I have to provide your email (as registered on athom portal) to allow you to download alpha version. So if you're interested - please send it to me in private message.

**Comment by Piotr-Grochowski** [comment]
v1.8.1 is available in the beta channel. Please test it and let me know if it works now.

**Comment by lindblomstefan** [comment]
Will do when home from work 👍

**Comment by lindblomstefan** [comment]
Could not wait :) I’ve added it successfully and will test it fully when I’m physically at the garage door.

**Comment by Piotr-Grochowski** [comment]
OK, great :)

**Comment by Piotr-Grochowski** [comment]
Hi! And...? Did it work? I am really curious if it works OK now.

**Comment by lindblomstefan** [comment]
Oh, sorry! Yes it worked beautifully :)

Remember that I have sensors connected to the gatebox? One for gate position closed and one for gate position open. The contact alarm implemented now (have not tested fully) I assume will only react to button pushed. This means that if I push the button for (let’s say) gate to open. I then change my mind, push the button again to stop and again to close it. Then the contact alarm will indicate open?

Is it possible to have Homey to get info from the gatebox itself on sensor status? If so I can remove the Xiaomi sensor I have now :)

By the way, tested to have the garage door to open based on when Homey recognized me coming home, worked like a charm 👍

Appreciate your work! Many thanks :)

**Comment by Piotr-Grochowski** [comment]
Great to hear it worked. 
Regarding sensor/alarm_contact in the driver - it is not connected with the button. The device object in Homey connects with your gateBox every 1sec (by default - you can change pooling interval in device's settings in Homey) and checks current position of the gate (gateBox gives values between 0 and 100 - 0 is fully closed, 100 - fully open, and between those values - partially open). So if the gate is closed (value = 0) then alarm_contact in Homey is set to "no", and if the gate is open (even partially, value >0), then alarm_contact in Homey is set to "yes". That's how it should work - please test it if you can in different scenarios (e.g. the one you've written) and let me know if it works as desired. if it doesn't work OK, please check what response do you get if you issue in your browser URL: http://192.168.2.164/api/gate/state (of course change to your IP, and issue that URL in a moment when contact alarm indicates wrong state). In the field "currentPos" there should be current position indicated as I written above.

**Comment by lindblomstefan** [comment]
Hi!

Clever :) I think that will do it then and that is exactly how it’s working with a regular single sensor, as the setup I have now with the Xiaomi door sensor. I’ll do some try outs when I have the opportunity.

This also mean that I can actually remove a lot or wires I have now to the two sensor connected to the gatebox that came along with it. This is getting better than I imagined :)

**Comment by Piotr-Grochowski** [comment]
Yes, you may remove Xiaomi sensor (if the tests will go OK of course), but I think you have to leave the wired sensors connected to gateBox, because gateBox knows the position of the gate (0-100) only thanks to the sensors (I think - of course you can check that yourself by disconnecting the wires and checking what the above URL gives you as a result in that situation).

**Comment by Piotr-Grochowski** [comment]
And after you make the tests please let me know that everything works ok (or I have to correct something), so I will be able to close this issue. Thanks for all your help!

**Comment by lindblomstefan** [comment]
I can verify that the alarm is always on but not when the door/gate is fully closed. It mirrors the Xiaomi door sensor I have. Have not been able to disconnect the sensors yet. Will let you know when I’ve been so.

**Comment by Piotr-Grochowski** [comment]
OK, then I think it works allright. So I will close this issue now. If you find any problem with the driver, please open a new bug (but hopefully there won't be any more bugs :P ).

**Comment by lindblomstefan** [comment]
Tested open/closed alarm this evening actually and it only works with the sensors connected. Works like a charm. Thanks for an awesome implementation.

The only thing I would like is to have a garage door as icon :)

**Comment by Piotr-Grochowski** [comment]
I'm happy to hear that.

Reg. the icon - I use official BleBox icons for their devices. Gatebox may be used for garage door, but also for gates etc. So I am not going to change this official icon.

I think it would be good if Athom would change a bit Homey software to allow users not only change the names but also the icons themselves.

**Comment by lindblomstefan** [comment]
Totally agree!

#closed

**Comment by lindblomstefan** [comment]
Hi Piotr!

It has been great since release. One thing that might be out of this implementation is function in HomeKit. In Homey button push trigger gate to move/stop and the same button/tile indicate sensor alarm.

I use Homeykit to get devices in HomeKit. That button ends up as a switch (can also chose lamp or fan). Do you know if it’s possible to implement in such way that HomeKit understand it as a Garagedoor? Maybe this is easy or not possible, I don’t know how this works.

Any idea?
@Piotr-Grochowski

**Comment by Piotr-Grochowski** [comment]
Hi,
I checked HomeyKit - in the description there is stated that:
"The following classes are supported: - Light (with RGB or Temperature) - Socket - Switch - Motionsensor (with lux and temp) - Doorlock - Door/Window sensor (with temp) - Thermostat - Windowblinds - Button"

So I think HomeyKit doesn't support garagedoor class so I don't think it's possible to export any device from Homey to HomeKit as a native garagedoor. 

Piotr

**Comment by lindblomstefan** [comment]
Hi,

Ok, got it. I’ll check that side then :)
