### ISSUE TITLE
Gatebox - Sensor values

### ISSUE THREAD

**Issue by lindblomstefan** [Piotr-Grochowski/homey-blebox#7]
The sensor values for open or closed does not reach Homey. I’ve checked that the sensors work properly with the RiCo app. There are two sensors connected to the gatebox to be able to determine if the gate/garage door is fully closed, fully open or somewhere in between.

I have not tried to remove and add the gatebox in Homey again due to rework of flows. If the could help I could do the effort. Any other information that could help?

**Comment by lindblomstefan** [comment]
@Piotr-Grochowski just checking if you seen this?

**Comment by Piotr-Grochowski** [comment]
Hello,
I missed that issue. I'll check it and I'll get back to you. Recently BleBox has made some changes to APIs, so I'll have to check if this also affected gatebox. Please tell me what is your firmware version and API level.

**Comment by lindblomstefan** [comment]
No worries:)

FW: 0.611
API type: gateBox

Is that what you are looking for?

**Comment by Piotr-Grochowski** [comment]
Reg. API - API level or API version or something like this. It will be a number like 20200229 or 20180604 or something like this.

**Comment by lindblomstefan** [comment]
Looked through the BleBox app and can’t seem to find it :/ Is it somewhere else?

**Comment by lindblomstefan** [comment]
@Piotr-Grochowski Anywhere else I can check for API version? I assume I have the latest since I’ve upgraded the hardware (Gatebox itself) so I guess that firmware calls upon the most current version. At least I hope so :)

**Comment by lindblomstefan** [comment]
Yeah but I don’t have that information there.
![535800AC-1406-43CC-9A92-6360708A8A0C](https://user-images.githubusercontent.com/46811709/92963975-9b2c2780-f473-11ea-9b7b-8ce74ccde2e9.jpeg)

**Comment by Piotr-Grochowski** [comment]
OK. So let's make some API checks. Please put this into your web browser:

**Comment by Piotr-Grochowski** [comment]
Sorry, I've hit Ctrl+Enter too fast :)

http://gatebox_ip/api/gate/state

And give me results - when the gate is opened, closed and somewhere in between.

**Comment by lindblomstefan** [comment]
{"currentPos":0,"desiredPos":50,"extraButtonType":1,"extraButtonRelayNumber":1,"extraButtonPulseTimeMs":800,"extraButtonInvert":0,"gateType":0,"gateRelayNumber":0,"gatePulseTimeMs":800,"gateInvert":0,"inputsType":0,"openLimitSwitchInputNumber":0,"closeLimitSwitchInputNumber":1}

**Comment by Piotr-Grochowski** [comment]
"currentPos":0 - gate is closed, in Homey there should be no alarm. Now please open the gate and issue the same.

**Comment by lindblomstefan** [comment]
Me too, to quick on Enter first time :)

**Comment by Piotr-Grochowski** [comment]
Hmmm.... Everything looks OK. if currentPos > 0 there should be alarm rised in gateBox device (contact alarm). Isn't it?

**Comment by Piotr-Grochowski** [comment]
Ahhh, and what about username and password - is it set OK in the driver?

**Comment by lindblomstefan** [comment]
Yepp correct

**Comment by Piotr-Grochowski** [comment]
Is your answer regarding alarm or user/pass?

**Comment by lindblomstefan** [comment]
Eeehhh hmmm Assumed it was correct since I can operate the gatebox from Homey

**Comment by lindblomstefan** [comment]
>Is your answer regarding alarm or user/pass?

@Piotr-Grochowski Alarm

**Comment by Piotr-Grochowski** [comment]
Then I don't get what the issue is. It operates as it should...

**Comment by Piotr-Grochowski** [comment]
Maybe it would be easier to use some chat like Skype, Messenger, etc? Do you use any?

**Comment by lindblomstefan** [comment]
Both user and pass is empty in advanced settings for the gatebox in Homey

**Comment by lindblomstefan** [comment]
Yeah, like everyone there is :) Try m.me/stefansprofile for messenger

**Comment by Piotr-Grochowski** [comment]
Just for future: I don't know why, but pooling hanged. Restarting the BleBox app solved the problem.

**Comment by lindblomstefan** [comment]
>Just for future: I don't know why, but pooling hanged. Restarting the BleBox app solved the problem.

@Piotr-Grochowski Thanks for excellent help!
